require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('../models/Category');

// All categories data extracted from App.jsx
const CATEGORIES_DATA = {
    // Group: Basic and Daily Life Vocabulary
    greetings: {
        title: 'Greetings & Phrases',
        group: 'Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Hei', english: 'Hello', context: 'Hei, hvordan går det?' },
            { norwegian: 'Ha det', english: 'Goodbye', context: 'Ha det bra, vi sees!' },
            { norwegian: 'Takk', english: 'Thank you', context: 'Takk for maten.' },
            { norwegian: 'Vær så snill', english: 'Please', context: 'Kan du hjelpe meg, vær så snill?' },
            { norwegian: 'Unnskyld', english: 'Excuse me', context: 'Unnskyld, hvor er toalettet?' },
            { norwegian: 'Hvordan går det?', english: 'How are you?', context: 'Hei, hvordan går det med deg?' },
            { norwegian: 'Bare bra', english: 'Just fine', context: 'Det går bare bra, takk.' },
            { norwegian: 'God morgen', english: 'Good morning', context: 'God morgen, har du sovet godt?' },
            { norwegian: 'God natt', english: 'Good night', context: 'God natt og sov godt.' },
            { norwegian: 'Velkommen', english: 'Welcome', context: 'Velkommen til oss!' },
            { norwegian: 'Ja', english: 'Yes', context: 'Ja, jeg vil gjerne ha kaffe.' },
            { norwegian: 'Nei', english: 'No', context: 'Nei, jeg liker ikke fisk.' },
            { norwegian: 'Kanskje', english: 'Maybe', context: 'Kanskje vi kan gå på kino?' },
            { norwegian: 'Jeg heter', english: 'My name is', context: 'Jeg heter Ola.' },
            { norwegian: 'Hyggelig', english: 'Nice to meet you', context: 'Hyggelig å hilse på deg.' },
            { norwegian: 'Vi sees', english: 'See you', context: 'Vi sees i morgen.' },
            { norwegian: 'Beklager', english: 'Sorry', context: 'Beklager at jeg er sen.' },
            { norwegian: 'Forstår du?', english: 'Do you understand?', context: 'Forstår du norsk?' },
            { norwegian: 'Hjelp', english: 'Help', context: 'Jeg trenger hjelp.' },
            { norwegian: 'Selvfølgelig', english: 'Of course', context: 'Selvfølgelig kan du det.' },
        ]
    },
    personal_info: {
        title: 'Personal Information',
        group: 'Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Navn', english: 'Name', context: 'Hva er ditt navn?' },
            { norwegian: 'Alder', english: 'Age', context: 'Hva er din alder?' },
            { norwegian: 'Jobb', english: 'Job', context: 'Jeg har en ny jobb.' },
            { norwegian: 'Yrke', english: 'Occupation', context: 'Hvilket yrke har du?' },
            { norwegian: 'Nasjonalitet', english: 'Nationality', context: 'Hva er din nasjonalitet?' },
            { norwegian: 'Land', english: 'Country', context: 'Hvilket land kommer du fra?' },
            { norwegian: 'By', english: 'City', context: 'Jeg bor i en stor by.' },
            { norwegian: 'Adresse', english: 'Address', context: 'Hva er din adresse?' },
            { norwegian: 'Telefonnummer', english: 'Phone number', context: 'Kan jeg få ditt telefonnummer?' },
            { norwegian: 'E-post', english: 'Email', context: 'Send meg en e-post.' },
            { norwegian: 'Student', english: 'Student', context: 'Jeg er student ved universitetet.' },
            { norwegian: 'Lærer', english: 'Teacher', context: 'Læreren vår er flink.' },
            { norwegian: 'Lege', english: 'Doctor', context: 'Legen hjalp meg.' },
            { norwegian: 'Ingeniør', english: 'Engineer', context: 'Hun jobber som ingeniør.' },
            { norwegian: 'Sykepleier', english: 'Nurse', context: 'Sykepleieren passer på pasientene.' },
            { norwegian: 'Pensjonist', english: 'Retiree', context: 'Min bestefar er pensjonist.' },
            { norwegian: 'Barn', english: 'Child', context: 'Jeg har et barn.' },
            { norwegian: 'Voksen', english: 'Adult', context: 'Billetten koster mer for en voksen.' },
            { norwegian: 'Mann', english: 'Man', context: 'En mann går på gaten.' },
            { norwegian: 'Kvinne', english: 'Woman', context: 'En kvinne kjører bilen.' },
        ]
    },
    family: {
        title: 'Family & People',
        group: 'Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Mor', english: 'Mother', context: 'Min mor er snill.' },
            { norwegian: 'Far', english: 'Father', context: 'Min far er sterk.' },
            { norwegian: 'Bror', english: 'Brother', context: 'Jeg har en lillebror.' },
            { norwegian: 'Søster', english: 'Sister', context: 'Min søster er eldre enn meg.' },
            { norwegian: 'Venn', english: 'Friend', context: 'Han er min beste venn.' },
            { norwegian: 'Familie', english: 'Family', context: 'Jeg er glad i min familie.' },
            { norwegian: 'Bestemor', english: 'Grandmother', context: 'Bestemor lager god mat.' },
            { norwegian: 'Bestefar', english: 'Grandfather', context: 'Bestefar forteller historier.' },
            { norwegian: 'Tante', english: 'Aunt', context: 'Tante kommer på besøk.' },
            { norwegian: 'Onkel', english: 'Uncle', context: 'Onkel er morsom.' },
            { norwegian: 'Sønn', english: 'Son', context: 'De har en sønn.' },
            { norwegian: 'Datter', english: 'Daughter', context: 'Deres datter går på skolen.' },
            { norwegian: 'Foreldre', english: 'Parents', context: 'Mine foreldre bor i Oslo.' },
            { norwegian: 'Kone', english: 'Wife', context: 'Hans kone er lege.' },
            { norwegian: 'Ektemann', english: 'Husband', context: 'Hennes ektemann er lærer.' },
            { norwegian: 'Kjæreste', english: 'Boyfriend/Girlfriend', context: 'Har du kjæreste?' },
            { norwegian: 'Nabo', english: 'Neighbor', context: 'Naboen vår er hyggelig.' },
            { norwegian: 'Kollega', english: 'Colleague', context: 'Jeg spiser lunsj med en kollega.' },
            { norwegian: 'Gutt', english: 'Boy', context: 'Gutten spiller fotball.' },
            { norwegian: 'Jente', english: 'Girl', context: 'Jenta leser en bok.' },
        ]
    },
    home: {
        title: 'Home & Furniture',
        group: 'Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Hus', english: 'House', context: 'Vi bor i et rødt hus.' },
            { norwegian: 'Rom', english: 'Room', context: 'Mitt rom er blått.' },
            { norwegian: 'Bord', english: 'Table', context: 'Maten står på bordet.' },
            { norwegian: 'Stol', english: 'Chair', context: 'Jeg sitter på en stol.' },
            { norwegian: 'Seng', english: 'Bed', context: 'Sengen er myk.' },
            { norwegian: 'Kjøkken', english: 'Kitchen', context: 'Vi lager mat på kjøkkenet.' },
            { norwegian: 'Bad', english: 'Bathroom', context: 'Badet er rent.' },
            { norwegian: 'Stue', english: 'Living room', context: 'Vi ser på TV i stuen.' },
            { norwegian: 'Sofa', english: 'Sofa', context: 'Sofaen er god å sitte i.' },
            { norwegian: 'Vindu', english: 'Window', context: 'Jeg ser ut av vinduet.' },
            { norwegian: 'Dør', english: 'Door', context: 'Kan du lukke døren?' },
            { norwegian: 'Gulv', english: 'Floor', context: 'Gulvet er kaldt.' },
            { norwegian: 'Tak', english: 'Ceiling/Roof', context: 'Taket er hvitt.' },
            { norwegian: 'Vegg', english: 'Wall', context: 'Vi maler veggen.' },
            { norwegian: 'Lampe', english: 'Lamp', context: 'Lampen lyser opp rommet.' },
            { norwegian: 'Teppe', english: 'Carpet/Rug', context: 'Teppet er mykt.' },
            { norwegian: 'Skap', english: 'Cupboard/Closet', context: 'Klærne henger i skapet.' },
            { norwegian: 'Kjøleskap', english: 'Refrigerator', context: 'Melken står i kjøleskapet.' },
            { norwegian: 'Komfyr', english: 'Stove', context: 'Komfyren er varm.' },
            { norwegian: 'Hage', english: 'Garden', context: 'Vi har blomster i hagen.' },
        ]
    },
    body_health: {
        title: 'Body & Health',
        group: 'Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Hode', english: 'Head', context: 'Jeg har vondt i hodet.' },
            { norwegian: 'Hånd', english: 'Hand', context: 'Vask hendene dine.' },
            { norwegian: 'Bein', english: 'Leg', context: 'Jeg brakk beinet.' },
            { norwegian: 'Lege', english: 'Doctor', context: 'Jeg må gå til legen.' },
            { norwegian: 'Syk', english: 'Sick', context: 'Jeg føler meg syk i dag.' },
            { norwegian: 'Frisk', english: 'Healthy', context: 'Spis sunt for å holde deg frisk.' },
            { norwegian: 'Medisin', english: 'Medicine', context: 'Du må ta medisinen din.' },
            { norwegian: 'Sykehus', english: 'Hospital', context: 'Sykehuset er stort.' },
            { norwegian: 'Vondt', english: 'Pain/Hurt', context: 'Det gjør vondt.' },
            { norwegian: 'Kropp', english: 'Body', context: 'Trening er bra for kroppen.' },
            { norwegian: 'Mage', english: 'Stomach', context: 'Jeg er mett i magen.' },
            { norwegian: 'Rygg', english: 'Back', context: 'Jeg har vondt i ryggen.' },
            { norwegian: 'Hjerte', english: 'Heart', context: 'Hjertet banker.' },
            { norwegian: 'Øye', english: 'Eye', context: 'Jeg fikk noe på øyet.' },
            { norwegian: 'Øre', english: 'Ear', context: 'Jeg har vondt i øret.' },
            { norwegian: 'Munn', english: 'Mouth', context: 'Lukk munnen når du tygger.' },
            { norwegian: 'Nese', english: 'Nose', context: 'Jeg er tett i nesen.' },
            { norwegian: 'Tann', english: 'Tooth', context: 'Jeg må til tannlegen.' },
            { norwegian: 'Hals', english: 'Neck/Throat', context: 'Jeg har vondt i halsen.' },
            { norwegian: 'Feber', english: 'Fever', context: 'Barnet har feber.' },
        ]
    },
    clothing: {
        title: 'Clothing',
        group: 'Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Skjorte', english: 'Shirt', context: 'Han har på seg en hvit skjorte.' },
            { norwegian: 'Bukse', english: 'Pants', context: 'Buksen er for lang.' },
            { norwegian: 'Sko', english: 'Shoes', context: 'Jeg trenger nye sko.' },
            { norwegian: 'Hatt', english: 'Hat', context: 'Han tok av seg hatten.' },
            { norwegian: 'Kjole', english: 'Dress', context: 'Hun har en fin kjole.' },
            { norwegian: 'Skjørt', english: 'Skirt', context: 'Skjørtet er blått.' },
            { norwegian: 'Jakke', english: 'Jacket', context: 'Ta på deg jakke, det er kaldt.' },
            { norwegian: 'Genser', english: 'Sweater', context: 'Genseren er varm.' },
            { norwegian: 'Sokker', english: 'Socks', context: 'Jeg har hull i sokkene.' },
            { norwegian: 'Lue', english: 'Beanie/Cap', context: 'Lue er godt om vinteren.' },
            { norwegian: 'Skjerf', english: 'Scarf', context: 'Skjerfet varmer halsen.' },
            { norwegian: 'Hansker', english: 'Gloves', context: 'Jeg mistet hanskene mine.' },
            { norwegian: 'Belte', english: 'Belt', context: 'Beltet er av skinn.' },
            { norwegian: 'Briller', english: 'Glasses', context: 'Jeg ser dårlig uten briller.' },
            { norwegian: 'Veske', english: 'Bag/Purse', context: 'Vesken er tung.' },
            { norwegian: 'Kåpe', english: 'Coat', context: 'Kåpen er elegant.' },
            { norwegian: 'Dress', english: 'Suit', context: 'Han bruker dress på jobb.' },
            { norwegian: 'Slips', english: 'Tie', context: 'Slipset er rødt.' },
            { norwegian: 'Støvler', english: 'Boots', context: 'Vi trenger støvler i regnet.' },
            { norwegian: 'T-skjorte', english: 'T-shirt', context: 'Jeg liker denne t-skjorten.' },
        ]
    },
    time: {
        title: 'Time & Dates',
        group: 'Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Dag', english: 'Day', context: 'Hvilken dag er det i dag?' },
            { norwegian: 'Uke', english: 'Week', context: 'Det er sju dager i en uke.' },
            { norwegian: 'Måned', english: 'Month', context: 'Januar er en måned.' },
            { norwegian: 'År', english: 'Year', context: 'Godt nytt år!' },
            { norwegian: 'Klokke', english: 'Clock/Watch', context: 'Hva er klokka?' },
            { norwegian: 'Nå', english: 'Now', context: 'Vi må gå nå.' },
            { norwegian: 'Mandag', english: 'Monday', context: 'Mandag er første dag i uken.' },
            { norwegian: 'Tirsdag', english: 'Tuesday', context: 'Vi sees på tirsdag.' },
            { norwegian: 'Onsdag', english: 'Wednesday', context: 'Onsdag er midt i uken.' },
            { norwegian: 'Torsdag', english: 'Thursday', context: 'Torsdag kommer etter onsdag.' },
            { norwegian: 'Fredag', english: 'Friday', context: 'Endelig er det fredag!' },
            { norwegian: 'Lørdag', english: 'Saturday', context: 'Lørdag er en fridag.' },
            { norwegian: 'Søndag', english: 'Sunday', context: 'Søndag er en rolig dag.' },
            { norwegian: 'Vår', english: 'Spring', context: 'Blomstene kommer om våren.' },
            { norwegian: 'Sommer', english: 'Summer', context: 'Jeg liker sommer og sol.' },
            { norwegian: 'Høst', english: 'Autumn', context: 'Løvet faller om høsten.' },
            { norwegian: 'Vinter', english: 'Winter', context: 'Det er kaldt om vinteren.' },
            { norwegian: 'Morgen', english: 'Morning', context: 'Jeg står opp tidlig om morgenen.' },
            { norwegian: 'Kveld', english: 'Evening', context: 'Vi ser film om kvelden.' },
            { norwegian: 'Natt', english: 'Night', context: 'Det er mørkt om natten.' },
        ]
    },

    // Group: Essential Concrete Concepts
    numbers: {
        title: 'Numbers',
        group: 'Essential Concrete Concepts',
        words: [
            { norwegian: 'En', english: 'One', context: 'Jeg har en bil.' },
            { norwegian: 'To', english: 'Two', context: 'Jeg har to brødre.' },
            { norwegian: 'Tre', english: 'Three', context: 'Alle gode ting er tre.' },
            { norwegian: 'Fire', english: 'Four', context: 'Bordet har fire bein.' },
            { norwegian: 'Fem', english: 'Five', context: 'Jeg har fem fingre på hver hånd.' },
            { norwegian: 'Seks', english: 'Six', context: 'Insektet har seks bein.' },
            { norwegian: 'Sju', english: 'Seven', context: 'Uken har sju dager.' },
            { norwegian: 'Åtte', english: 'Eight', context: 'Edderkoppen har åtte bein.' },
            { norwegian: 'Ni', english: 'Nine', context: 'Katten har ni liv.' },
            { norwegian: 'Ti', english: 'Ten', context: 'Jeg har ti tær.' },
            { norwegian: 'Elleve', english: 'Eleven', context: 'Klokken er elleve.' },
            { norwegian: 'Tolv', english: 'Twelve', context: 'Det er tolv måneder i året.' },
            { norwegian: 'Tjue', english: 'Twenty', context: 'Det koster tjue kroner.' },
            { norwegian: 'Hundre', english: 'Hundred', context: 'Jeg løp hundre meter.' },
            { norwegian: 'Tusen', english: 'Thousand', context: 'Det var tusen mennesker der.' },
            { norwegian: 'Første', english: 'First', context: 'Han kom på første plass.' },
            { norwegian: 'Andre', english: 'Second', context: 'Dette er andre gang jeg prøver.' },
            { norwegian: 'Halv', english: 'Half', context: 'Jeg vil ha en halv kake.' },
            { norwegian: 'Mange', english: 'Many', context: 'Det er mange folk her.' },
            { norwegian: 'Få', english: 'Few', context: 'Det er få biler på veien.' },
        ]
    },
    colors: {
        title: 'Colors',
        group: 'Essential Concrete Concepts',
        words: [
            { norwegian: 'Rød', english: 'Red', context: 'Eplet er rødt.' },
            { norwegian: 'Blå', english: 'Blue', context: 'Himmelen er blå.' },
            { norwegian: 'Grønn', english: 'Green', context: 'Gresset er grønt.' },
            { norwegian: 'Gul', english: 'Yellow', context: 'Solen er gul.' },
            { norwegian: 'Svart', english: 'Black', context: 'Katten er svart.' },
            { norwegian: 'Hvit', english: 'White', context: 'Snøen er hvit.' },
            { norwegian: 'Lilla', english: 'Purple', context: 'Blomsten er lilla.' },
            { norwegian: 'Oransje', english: 'Orange', context: 'Appelsinen er oransje.' },
            { norwegian: 'Grå', english: 'Grey', context: 'Elefanten er grå.' },
            { norwegian: 'Brun', english: 'Brown', context: 'Bjørnen er brun.' },
            { norwegian: 'Rosa', english: 'Pink', context: 'Grisen er rosa.' },
            { norwegian: 'Turkis', english: 'Turquoise', context: 'Vannet er turkis.' },
            { norwegian: 'Gull', english: 'Gold', context: 'Ringen er av gull.' },
            { norwegian: 'Sølv', english: 'Silver', context: 'Bestikket er av sølv.' },
            { norwegian: 'Beige', english: 'Beige', context: 'Sofaen er beige.' },
            { norwegian: 'Marineblå', english: 'Navy', context: 'Uniformen er marineblå.' },
            { norwegian: 'Lyseblå', english: 'Light Blue', context: 'Skjorten er lyseblå.' },
            { norwegian: 'Mørkegrønn', english: 'Dark Green', context: 'Skogen er mørkegrønn.' },
            { norwegian: 'Fiolett', english: 'Violet', context: 'Lyset er fiolett.' },
            { norwegian: 'Indigo', english: 'Indigo', context: 'Fargen er indigo.' },
        ]
    },
    food_drink: {
        title: 'Food & Drink',
        group: 'Essential Concrete Concepts',
        words: [
            { norwegian: 'Mat', english: 'Food', context: 'Vi trenger mat for å leve.' },
            { norwegian: 'Vann', english: 'Water', context: 'Jeg drikker vann hver dag.' },
            { norwegian: 'Brød', english: 'Bread', context: 'Jeg spiser brød til frokost.' },
            { norwegian: 'Kjøtt', english: 'Meat', context: 'Vi griller kjøtt om sommeren.' },
            { norwegian: 'Kaffe', english: 'Coffee', context: 'Mange voksne drikker kaffe.' },
            { norwegian: 'Frukt', english: 'Fruit', context: 'Frukt smaker godt.' },
            { norwegian: 'Grønnsaker', english: 'Vegetables', context: 'Grønnsaker er sunt.' },
            { norwegian: 'Ost', english: 'Cheese', context: 'Ost er godt på brødskiven.' },
            { norwegian: 'Eple', english: 'Apple', context: 'Et eple om dagen er bra.' },
            { norwegian: 'Banan', english: 'Banana', context: 'Aper liker bananer.' },
            { norwegian: 'Fisk', english: 'Fish', context: 'Fisk er sunt.' },
            { norwegian: 'Melk', english: 'Milk', context: 'Melk kommer fra kua.' },
            { norwegian: 'Te', english: 'Tea', context: 'Vil du ha en kopp te?' },
            { norwegian: 'Sukker', english: 'Sugar', context: 'Sukker er søtt.' },
            { norwegian: 'Salt', english: 'Salt', context: 'Vi bruker salt i maten.' },
            { norwegian: 'Smør', english: 'Butter', context: 'Smør smelter i pannen.' },
            { norwegian: 'Egg', english: 'Egg', context: 'Høna legger egg.' },
            { norwegian: 'Kake', english: 'Cake', context: 'Vi spiser kake i bursdager.' },
            { norwegian: 'Is', english: 'Ice Cream', context: 'Is er kaldt og godt.' },
            { norwegian: 'Potet', english: 'Potato', context: 'Poteter vokser i jorden.' },
        ]
    },
    places: {
        title: 'Places & Directions',
        group: 'Essential Concrete Concepts',
        words: [
            { norwegian: 'By', english: 'City', context: 'Oslo er en by.' },
            { norwegian: 'Gate', english: 'Street', context: 'Vi bor i denne gaten.' },
            { norwegian: 'Bank', english: 'Bank', context: 'Jeg skal i banken.' },
            { norwegian: 'Restaurant', english: 'Restaurant', context: 'Vi spiser på restaurant.' },
            { norwegian: 'Venstre', english: 'Left', context: 'Ta til venstre i krysset.' },
            { norwegian: 'Høyre', english: 'Right', context: 'Høyre hånd er den du skriver med.' },
            { norwegian: 'Rett fram', english: 'Straight', context: 'Gå rett fram.' },
            { norwegian: 'Skole', english: 'School', context: 'Barna går på skolen.' },
            { norwegian: 'Butikk', english: 'Shop/Store', context: 'Jeg handler i butikken.' },
            { norwegian: 'Hjem', english: 'Home', context: 'Jeg vil hjem.' },
            { norwegian: 'Jobb', english: 'Work', context: 'Han er på jobb.' },
            { norwegian: 'Park', english: 'Park', context: 'Vi leker i parken.' },
            { norwegian: 'Hotell', english: 'Hotel', context: 'Vi bor på hotell i ferien.' },
            { norwegian: 'Flyplass', english: 'Airport', context: 'Flyet lander på flyplassen.' },
            { norwegian: 'Stasjon', english: 'Station', context: 'Toget står på stasjonen.' },
            { norwegian: 'Nord', english: 'North', context: 'Nord-Norge er vakkert.' },
            { norwegian: 'Sør', english: 'South', context: 'Det er varmere i sør.' },
            { norwegian: 'Øst', english: 'East', context: 'Solen står opp i øst.' },
            { norwegian: 'Vest', english: 'West', context: 'Solen går ned i vest.' },
            { norwegian: 'Kart', english: 'Map', context: 'Vi trenger et kart for å finne veien.' },
        ]
    },
    nature: {
        title: 'Weather & Nature',
        group: 'Essential Concrete Concepts',
        words: [
            { norwegian: 'Sol', english: 'Sun', context: 'Solen skinner.' },
            { norwegian: 'Regn', english: 'Rain', context: 'Det kommer regn i dag.' },
            { norwegian: 'Tre', english: 'Tree', context: 'Treet er høyt.' },
            { norwegian: 'Dyr', english: 'Animal', context: 'Hunden er et dyr.' },
            { norwegian: 'Snø', english: 'Snow', context: 'Barna leker i snøen.' },
            { norwegian: 'Vind', english: 'Wind', context: 'Vinden blåser kraftig.' },
            { norwegian: 'Sky', english: 'Cloud', context: 'Det er ingen skyer på himmelen.' },
            { norwegian: 'Blomst', english: 'Flower', context: 'Blomsten lukter godt.' },
            { norwegian: 'Fjell', english: 'Mountain', context: 'Vi skal gå på fjellet.' },
            { norwegian: 'Skog', english: 'Forest', context: 'Det er mange trær i skogen.' },
            { norwegian: 'Sjø', english: 'Sea', context: 'Sjøen er blå.' },
            { norwegian: 'Elv', english: 'River', context: 'Elven renner fort.' },
            { norwegian: 'Strand', english: 'Beach', context: 'Vi bader på stranden.' },
            { norwegian: 'Måne', english: 'Moon', context: 'Månen lyser om natten.' },
            { norwegian: 'Stjerne', english: 'Star', context: 'Se på stjernene.' },
            { norwegian: 'Gress', english: 'Grass', context: 'Gresset er grønt.' },
            { norwegian: 'Stein', english: 'Stone', context: 'Steinen er hard.' },
            { norwegian: 'Vær', english: 'Weather', context: 'Været er fint i dag.' },
            { norwegian: 'Lyn', english: 'Lightning', context: 'Lyn og torden.' },
            { norwegian: 'Tåke', english: 'Fog', context: 'Det er mye tåke ute.' },
        ]
    },
    objects: {
        title: 'Common Objects',
        group: 'Essential Concrete Concepts',
        words: [
            { norwegian: 'Telefon', english: 'Phone', context: 'Jeg snakker i telefonen.' },
            { norwegian: 'Bil', english: 'Car', context: 'Bilen kjører fort.' },
            { norwegian: 'Bok', english: 'Book', context: 'Jeg leser en bok.' },
            { norwegian: 'Penger', english: 'Money', context: 'Har du penger?' },
            { norwegian: 'Nøkkel', english: 'Key', context: 'Jeg mistet nøkkelen min.' },
            { norwegian: 'Datamaskin', english: 'Computer', context: 'Jeg jobber på datamaskinen.' },
            { norwegian: 'Penn', english: 'Pen', context: 'Kan jeg låne en penn?' },
            { norwegian: 'Papir', english: 'Paper', context: 'Skriv det på papiret.' },
            { norwegian: 'Sykkel', english: 'Bicycle', context: 'Jeg sykler til jobben.' },
            { norwegian: 'Buss', english: 'Bus', context: 'Vi tar bussen.' },
            { norwegian: 'Tog', english: 'Train', context: 'Toget går klokken åtte.' },
            { norwegian: 'Klokke', english: 'Clock', context: 'Klokken henger på veggen.' },
            { norwegian: 'Briller', english: 'Glasses', context: 'Jeg trenger briller for å lese.' },
            { norwegian: 'Lommebok', english: 'Wallet', context: 'Lommeboken ligger i lommen.' },
            { norwegian: 'Sekk', english: 'Backpack', context: 'Sekken er tung.' },
            { norwegian: 'Kniv', english: 'Knife', context: 'Vi skjærer brød med kniv.' },
            { norwegian: 'Gaffel', english: 'Fork', context: 'Vi spiser med gaffel.' },
            { norwegian: 'Skje', english: 'Spoon', context: 'Vi spiser suppe med skje.' },
            { norwegian: 'Tallerken', english: 'Plate', context: 'Maten ligger på tallerkenen.' },
            { norwegian: 'Glass', english: 'Glass', context: 'Kan jeg få et glass vann?' },
        ]
    },

    // Group: Abstract & Descriptive Concepts
    adjectives: {
        title: 'Basic Adjectives',
        group: 'Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'God', english: 'Good', context: 'Maten smaker godt.' },
            { norwegian: 'Dårlig', english: 'Bad', context: 'Været er dårlig.' },
            { norwegian: 'Stor', english: 'Big', context: 'Elefanten er stor.' },
            { norwegian: 'Liten', english: 'Small', context: 'Musen er liten.' },
            { norwegian: 'Varm', english: 'Hot', context: 'Kaffen er varm.' },
            { norwegian: 'Kald', english: 'Cold', context: 'Isen er kald.' },
            { norwegian: 'Enkel', english: 'Easy', context: 'Oppgaven var enkel.' },
            { norwegian: 'Vanskelig', english: 'Difficult', context: 'Norsk kan være vanskelig.' },
            { norwegian: 'Ny', english: 'New', context: 'Jeg har en ny bil.' },
            { norwegian: 'Gammel', english: 'Old', context: 'Huset er gammelt.' },
            { norwegian: 'Ung', english: 'Young', context: 'Han er ung.' },
            { norwegian: 'Lang', english: 'Long', context: 'Veien er lang.' },
            { norwegian: 'Kort', english: 'Short', context: 'Dagen er kort.' },
            { norwegian: 'Høy', english: 'High/Tall', context: 'Fjellet er høyt.' },
            { norwegian: 'Lav', english: 'Low', context: 'Treet er lavt.' },
            { norwegian: 'Dyr', english: 'Expensive', context: 'Bilen er dyr.' },
            { norwegian: 'Billig', english: 'Cheap', context: 'Mat er billig her.' },
            { norwegian: 'Vakker', english: 'Beautiful', context: 'Naturen er vakker.' },
            { norwegian: 'Stygg', english: 'Ugly', context: 'Det var en stygg farge.' },
            { norwegian: 'Glad', english: 'Happy', context: 'Jeg er glad i dag.' },
        ]
    },
    frequency: {
        title: 'Frequency & Quantity',
        group: 'Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'Alltid', english: 'Always', context: 'Jeg pusser alltid tennene.' },
            { norwegian: 'Aldri', english: 'Never', context: 'Jeg spiser aldri snegler.' },
            { norwegian: 'Noen ganger', english: 'Sometimes', context: 'Noen ganger går jeg på kino.' },
            { norwegian: 'Ofte', english: 'Often', context: 'Vi besøker dem ofte.' },
            { norwegian: 'Sjelden', english: 'Rarely', context: 'Det snør sjelden her.' },
            { norwegian: 'Mye', english: 'Much', context: 'Det er mye mat her.' },
            { norwegian: 'Mange', english: 'Many', context: 'Det er mange mennesker her.' },
            { norwegian: 'Litt', english: 'A little', context: 'Jeg vil ha litt vann.' },
            { norwegian: 'Få', english: 'Few', context: 'Det er få dager igjen.' },
            { norwegian: 'Nok', english: 'Enough', context: 'Det er nok mat til alle.' },
            { norwegian: 'Alt', english: 'Everything', context: 'Jeg spiste alt.' },
            { norwegian: 'Ingenting', english: 'Nothing', context: 'Jeg hørte ingenting.' },
            { norwegian: 'Alle', english: 'Everyone/All', context: 'Alle var glade.' },
            { norwegian: 'Ingen', english: 'No one/None', context: 'Ingen var hjemme.' },
            { norwegian: 'Mer', english: 'More', context: 'Vil du ha mer?' },
            { norwegian: 'Mindre', english: 'Less', context: 'Jeg vil ha mindre sukker.' },
            { norwegian: 'Hele', english: 'Whole', context: 'Hele dagen.' },
            { norwegian: 'Halve', english: 'Half', context: 'Halve kaken er borte.' },
            { norwegian: 'Nesten', english: 'Almost', context: 'Vi er nesten fremme.' },
            { norwegian: 'Kanskje', english: 'Maybe', context: 'Kanskje det regner.' },
        ]
    },
    questions: {
        title: 'Question Words',
        group: 'Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'Hvem', english: 'Who', context: 'Hvem er det?' },
            { norwegian: 'Hva', english: 'What', context: 'Hva heter du?' },
            { norwegian: 'Hvor', english: 'Where', context: 'Hvor bor du?' },
            { norwegian: 'Når', english: 'When', context: 'Når kommer du?' },
            { norwegian: 'Hvorfor', english: 'Why', context: 'Hvorfor gråter du?' },
            { norwegian: 'Hvordan', english: 'How', context: 'Hvordan går det?' },
            { norwegian: 'Hvilken', english: 'Which', context: 'Hvilken bil er din?' },
            { norwegian: 'Hvor mye', english: 'How much', context: 'Hvor mye koster det?' },
            { norwegian: 'Hvor mange', english: 'How many', context: 'Hvor mange brødre har du?' },
            { norwegian: 'Hvor lenge', english: 'How long', context: 'Hvor lenge skal du være her?' },
            { norwegian: 'Hvor langt', english: 'How far', context: 'Hvor langt er det til Oslo?' },
            { norwegian: 'Hva slags', english: 'What kind', context: 'Hva slags musikk liker du?' },
            { norwegian: 'Når som helst', english: 'Anytime', context: 'Du kan komme når som helst.' },
            { norwegian: 'Hvem sin', english: 'Whose', context: 'Hvem sin bok er dette?' },
            { norwegian: 'Hvorfra', english: 'Where from', context: 'Hvorfra kommer du?' },
            { norwegian: 'Hvorhen', english: 'Where to', context: 'Hvorhen skal du?' },
            { norwegian: 'Der', english: 'There', context: 'Se der!' },
            { norwegian: 'Her', english: 'Here', context: 'Kom hit.' },
            { norwegian: 'Fordi', english: 'Because', context: 'Fordi jeg er sulten.' },
            { norwegian: 'Hvis', english: 'If', context: 'Hvis det regner, blir vi inne.' },
        ]
    },
    verbs: {
        title: 'Verbs',
        group: 'Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'Å spise', english: 'To eat', context: 'Jeg liker å spise pizza.' },
            { norwegian: 'Å drikke', english: 'To drink', context: 'Det er viktig å drikke vann.' },
            { norwegian: 'Å sove', english: 'To sleep', context: 'Jeg liker å sove lenge.' },
            { norwegian: 'Å gå', english: 'To walk', context: 'Vi skal gå en tur.' },
            { norwegian: 'Å løpe', english: 'To run', context: 'Han kan løpe veldig fort.' },
            { norwegian: 'Å snakke', english: 'To talk', context: 'Vi liker å snakke sammen.' },
            { norwegian: 'Å lese', english: 'To read', context: 'Jeg skal lese en bok.' },
            { norwegian: 'Å skrive', english: 'To write', context: 'Hun skal skrive et brev.' },
            { norwegian: 'Å se', english: 'To see', context: 'Jeg kan se deg.' },
            { norwegian: 'Å høre', english: 'To hear', context: 'Kan du høre musikken?' },
            { norwegian: 'Å leke', english: 'To play', context: 'Barna liker å leke ute.' },
            { norwegian: 'Å jobbe', english: 'To work', context: 'Han må jobbe i morgen.' },
            { norwegian: 'Å lære', english: 'To learn', context: 'Jeg vil lære norsk.' },
            { norwegian: 'Å kjøpe', english: 'To buy', context: 'Vi skal kjøpe mat.' },
            { norwegian: 'Å selge', english: 'To sell', context: 'Han skal selge bilen sin.' },
            { norwegian: 'Å sitte', english: 'To sit', context: 'Du kan sitte på stolen.' },
            { norwegian: 'Å stå', english: 'To stand', context: 'Du må stå i kø.' },
            { norwegian: 'Å hoppe', english: 'To jump', context: 'Kan du hoppe høyt?' },
            { norwegian: 'Å svømme', english: 'To swim', context: 'Vi skal svømme i sjøen.' },
            { norwegian: 'Å fly', english: 'To fly', context: 'Fugler kan fly.' },
        ]
    },

    // --- LEVEL 2 CATEGORIES ---

    // Group: Level 2: Basic and Daily Life Vocabulary
    greetings_l2: {
        title: 'Greetings (L2)',
        group: 'Level 2: Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'God ettermiddag', english: 'Good afternoon', context: 'God ettermiddag, mine damer og herrer.' },
            { norwegian: 'God kveld', english: 'Good evening', context: 'God kveld, velkommen til festen.' },
            { norwegian: 'Lykke til', english: 'Good luck', context: 'Lykke til med eksamen!' },
            { norwegian: 'Gratulerer', english: 'Congratulations', context: 'Gratulerer med dagen!' },
            { norwegian: 'Ingen årsak', english: 'You are welcome', context: 'Takk! - Ingen årsak.' },
            { norwegian: 'Ha en fin dag', english: 'Have a nice day', context: 'Ha en fin dag på jobben.' },
            { norwegian: 'Vi snakkes', english: 'Talk to you later', context: 'Vi snakkes i morgen.' },
            { norwegian: 'Hva skjer?', english: 'What is up?', context: 'Hei, hva skjer?' },
            { norwegian: 'Alt i orden', english: 'Everything is fine', context: 'Ikke bekymre deg, alt i orden.' },
            { norwegian: 'Ta det med ro', english: 'Take it easy', context: 'Ta det med ro, vi har god tid.' },
        ]
    },
    personal_info_l2: {
        title: 'Personal Info (L2)',
        group: 'Level 2: Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Fødselsdato', english: 'Date of birth', context: 'Skriv din fødselsdato her.' },
            { norwegian: 'Sivilstatus', english: 'Marital status', context: 'Hva er din sivilstatus?' },
            { norwegian: 'Gift', english: 'Married', context: 'Jeg er gift.' },
            { norwegian: 'Ugift', english: 'Single', context: 'Han er ugift.' },
            { norwegian: 'Skilt', english: 'Divorced', context: 'De er skilt.' },
            { norwegian: 'Enke', english: 'Widow', context: 'Hun er enke.' },
            { norwegian: 'Statsborgerskap', english: 'Citizenship', context: 'Jeg har norsk statsborgerskap.' },
            { norwegian: 'Kjønn', english: 'Gender', context: 'Kjønn: Mann eller Kvinne.' },
            { norwegian: 'Etternavn', english: 'Surname', context: 'Mitt etternavn er Hansen.' },
            { norwegian: 'Fornavn', english: 'First name', context: 'Mitt fornavn er Ola.' },
        ]
    },
    family_l2: {
        title: 'Family (L2)',
        group: 'Level 2: Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Svigermor', english: 'Mother-in-law', context: 'Min svigermor er hyggelig.' },
            { norwegian: 'Svigerfar', english: 'Father-in-law', context: 'Min svigerfar liker å fiske.' },
            { norwegian: 'Svoger', english: 'Brother-in-law', context: 'Min svoger bor i Bergen.' },
            { norwegian: 'Svigerinne', english: 'Sister-in-law', context: 'Min svigerinne er lærer.' },
            { norwegian: 'Nevø', english: 'Nephew', context: 'Min nevø er fem år.' },
            { norwegian: 'Niese', english: 'Niece', context: 'Min niese går på skolen.' },
            { norwegian: 'Fetter', english: 'Cousin (male)', context: 'Jeg leker med min fetter.' },
            { norwegian: 'Kusine', english: 'Cousin (female)', context: 'Min kusine er like gammel som meg.' },
            { norwegian: 'Ektepar', english: 'Married couple', context: 'De er et lykkelig ektepar.' },
            { norwegian: 'Slektning', english: 'Relative', context: 'Han er en fjern slektning.' },
        ]
    },
    home_l2: {
        title: 'Home (L2)',
        group: 'Level 2: Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Kjeller', english: 'Basement', context: 'Vi har en bod i kjelleren.' },
            { norwegian: 'Loft', english: 'Attic', context: 'Det er støvete på loftet.' },
            { norwegian: 'Garasje', english: 'Garage', context: 'Bilen står i garasjen.' },
            { norwegian: 'Veranda', english: 'Porch/Veranda', context: 'Vi sitter på verandaen om sommeren.' },
            { norwegian: 'Peis', english: 'Fireplace', context: 'Vi fyrer i peisen.' },
            { norwegian: 'Oppvaskmaskin', english: 'Dishwasher', context: 'Sett tallerkenen i oppvaskmaskinen.' },
            { norwegian: 'Vaskemaskin', english: 'Washing machine', context: 'Klærne er i vaskemaskinen.' },
            { norwegian: 'Tørketrommel', english: 'Dryer', context: 'Tørketrommelen er ferdig.' },
            { norwegian: 'Strykejern', english: 'Iron', context: 'Jeg må bruke strykejern på skjorten.' },
            { norwegian: 'Støvsuger', english: 'Vacuum cleaner', context: 'Støvsugeren bråker.' },
        ]
    },
    body_health_l2: {
        title: 'Body & Health (L2)',
        group: 'Level 2: Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Hjerne', english: 'Brain', context: 'Hjernen tenker.' },
            { norwegian: 'Lunge', english: 'Lung', context: 'Vi puster med lungene.' },
            { norwegian: 'Muskel', english: 'Muscle', context: 'Han har store muskler.' },
            { norwegian: 'Skjelett', english: 'Skeleton', context: 'Skjelettet holder kroppen oppe.' },
            { norwegian: 'Hud', english: 'Skin', context: 'Huden beskytter kroppen.' },
            { norwegian: 'Blod', english: 'Blood', context: 'Blodet er rødt.' },
            { norwegian: 'Smitte', english: 'Infection/Contagion', context: 'Vask hendene for å unngå smitte.' },
            { norwegian: 'Forkjølelse', english: 'Cold (illness)', context: 'Jeg har en forkjølelse.' },
            { norwegian: 'Hodepine', english: 'Headache', context: 'Jeg har sterk hodepine.' },
            { norwegian: 'Tannlege', english: 'Dentist', context: 'Tannlegen sjekker tennene.' },
        ]
    },
    clothing_l2: {
        title: 'Clothing (L2)',
        group: 'Level 2: Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Undertøy', english: 'Underwear', context: 'Husk rent undertøy.' },
            { norwegian: 'Badedrakt', english: 'Swimsuit', context: 'Hun har ny badedrakt.' },
            { norwegian: 'Regnjakke', english: 'Raincoat', context: 'Ta på regnjakke når det regner.' },
            { norwegian: 'Støvler', english: 'Boots', context: 'Gummistøvler er bra i gjørma.' },
            { norwegian: 'Tøfler', english: 'Slippers', context: 'Tøfler er varme inne.' },
            { norwegian: 'Smykke', english: 'Jewelry/Necklace', context: 'Hun har et fint smykke.' },
            { norwegian: 'Armbånd', english: 'Bracelet', context: 'Armbåndet er av sølv.' },
            { norwegian: 'Øredobber', english: 'Earrings', context: 'Hun har gulløredobber.' },
            { norwegian: 'Paraply', english: 'Umbrella', context: 'Ta med paraply.' },
            { norwegian: 'Glidelås', english: 'Zipper', context: 'Glidelåsen er ødelagt.' },
        ]
    },
    time_l2: {
        title: 'Time (L2)',
        group: 'Level 2: Basic and Daily Life Vocabulary',
        words: [
            { norwegian: 'Sekund', english: 'Second', context: 'Vent et sekund.' },
            { norwegian: 'Minutt', english: 'Minute', context: 'Det tar fem minutter.' },
            { norwegian: 'Time', english: 'Hour', context: 'Filmen varer i to timer.' },
            { norwegian: 'Døgn', english: '24 hours', context: 'Det er 24 timer i et døgn.' },
            { norwegian: 'Fortid', english: 'Past', context: 'Det skjedde i fortiden.' },
            { norwegian: 'Fremtid', english: 'Future', context: 'Hva bringer fremtiden?' },
            { norwegian: 'Nåtid', english: 'Present', context: 'Vi lever i nåtiden.' },
            { norwegian: 'Helg', english: 'Weekend', context: 'God helg!' },
            { norwegian: 'Hverdag', english: 'Weekday', context: 'Mandag til fredag er hverdager.' },
            { norwegian: 'Ferie', english: 'Vacation/Holiday', context: 'Vi skal på ferie.' },
        ]
    },

    // Group: Level 2: Essential Concrete Concepts
    numbers_l2: {
        title: 'Numbers (L2)',
        group: 'Level 2: Essential Concrete Concepts',
        words: [
            { norwegian: 'Null', english: 'Zero', context: 'Det er null grader ute.' },
            { norwegian: 'Tretten', english: 'Thirteen', context: 'Tretten er et ulykkestall.' },
            { norwegian: 'Fjorten', english: 'Fourteen', context: 'Han er fjorten år.' },
            { norwegian: 'Femten', english: 'Fifteen', context: 'Klokken er femten.' },
            { norwegian: 'Seksten', english: 'Sixteen', context: 'Seksten kommer etter femten.' },
            { norwegian: 'Sytten', english: 'Seventeen', context: 'Syttende mai er nasjonaldagen.' },
            { norwegian: 'Atten', english: 'Eighteen', context: 'Du er myndig når du er atten.' },
            { norwegian: 'Nitten', english: 'Nineteen', context: 'Nitten år gammel.' },
            { norwegian: 'Tredve', english: 'Thirty', context: 'Tredve dager i april.' },
            { norwegian: 'Million', english: 'Million', context: 'En million kroner.' },
        ]
    },
    colors_l2: {
        title: 'Colors (L2)',
        group: 'Level 2: Essential Concrete Concepts',
        words: [
            { norwegian: 'Lysegrønn', english: 'Light Green', context: 'Bladene er lysegrønne.' },
            { norwegian: 'Mørkeblå', english: 'Dark Blue', context: 'Havet er mørkeblått.' },
            { norwegian: 'Burgunder', english: 'Burgundy', context: 'Kjolen er burgunder.' },
            { norwegian: 'Sennepsgul', english: 'Mustard Yellow', context: 'Sennepsgul er moderne.' },
            { norwegian: 'Kremhvit', english: 'Cream', context: 'Veggene er kremhvite.' },
            { norwegian: 'Gjennomsiktig', english: 'Transparent', context: 'Glasset er gjennomsiktig.' },
            { norwegian: 'Fargerik', english: 'Colorful', context: 'Fuglen er fargerik.' },
            { norwegian: 'Ensfarget', english: 'Solid color', context: 'Skjorten er ensfarget.' },
            { norwegian: 'Mønstret', english: 'Patterned', context: 'Teppet er mønstret.' },
            { norwegian: 'Skinnende', english: 'Shiny', context: 'Bilen er skinnende ren.' },
        ]
    },
    food_drink_l2: {
        title: 'Food (L2)',
        group: 'Level 2: Essential Concrete Concepts',
        words: [
            { norwegian: 'Agurk', english: 'Cucumber', context: 'Agurk er godt i salat.' },
            { norwegian: 'Tomat', english: 'Tomato', context: 'Tomatsuppe er godt.' },
            { norwegian: 'Løk', english: 'Onion', context: 'Løk får meg til å gråte.' },
            { norwegian: 'Hvitløk', english: 'Garlic', context: 'Hvitløk smaker sterkt.' },
            { norwegian: 'Kylling', english: 'Chicken', context: 'Vi spiser kylling til middag.' },
            { norwegian: 'Laks', english: 'Salmon', context: 'Norsk laks er kjent.' },
            { norwegian: 'Reker', english: 'Shrimp', context: 'Vi spiser reker på brødskiven.' },
            { norwegian: 'Yoghurt', english: 'Yogurt', context: 'Yoghurt til frokost.' },
            { norwegian: 'Nøtter', english: 'Nuts', context: 'Ekornet spiser nøtter.' },
            { norwegian: 'Sjokolade', english: 'Chocolate', context: 'Jeg elsker sjokolade.' },
        ]
    },
    places_l2: {
        title: 'Places (L2)',
        group: 'Level 2: Essential Concrete Concepts',
        words: [
            { norwegian: 'Bibliotek', english: 'Library', context: 'Jeg låner bøker på biblioteket.' },
            { norwegian: 'Kino', english: 'Cinema', context: 'Vi ser film på kino.' },
            { norwegian: 'Teater', english: 'Theater', context: 'Skuespillerne står på scenen i teateret.' },
            { norwegian: 'Apotek', english: 'Pharmacy', context: 'Vi kjøper medisin på apoteket.' },
            { norwegian: 'Bakeri', english: 'Bakery', context: 'Bakeriet selger ferske boller.' },
            { norwegian: 'Frisør', english: 'Hairdresser', context: 'Jeg klipper meg hos frisøren.' },
            { norwegian: 'Kirke', english: 'Church', context: 'Kirken er gammel.' },
            { norwegian: 'Slott', english: 'Castle/Palace', context: 'Kongen bor i slottet.' },
            { norwegian: 'Bro', english: 'Bridge', context: 'Vi kjører over broen.' },
            { norwegian: 'Torg', english: 'Square/Market', context: 'Vi møtes på torget.' },
        ]
    },
    nature_l2: {
        title: 'Nature (L2)',
        group: 'Level 2: Essential Concrete Concepts',
        words: [
            { norwegian: 'Bølge', english: 'Wave', context: 'Bølgene slår mot stranden.' },
            { norwegian: 'Øy', english: 'Island', context: 'De bor på en øy.' },
            { norwegian: 'Dal', english: 'Valley', context: 'Dalen er dyp.' },
            { norwegian: 'Fjord', english: 'Fjord', context: 'Norge har mange fjorder.' },
            { norwegian: 'Isbre', english: 'Glacier', context: 'Isbreen smelter.' },
            { norwegian: 'Nordlys', english: 'Northern Lights', context: 'Nordlyset er magisk.' },
            { norwegian: 'Midnattssol', english: 'Midnight Sun', context: 'Solen skinner om natten.' },
            { norwegian: 'Storm', english: 'Storm', context: 'Det var en kraftig storm.' },
            { norwegian: 'Torden', english: 'Thunder', context: 'Jeg er redd for torden.' },
            { norwegian: 'Regnbue', english: 'Rainbow', context: 'Regnbuen har mange farger.' },
        ]
    },
    objects_l2: {
        title: 'Objects (L2)',
        group: 'Level 2: Essential Concrete Concepts',
        words: [
            { norwegian: 'Saks', english: 'Scissors', context: 'Klipp papiret med saks.' },
            { norwegian: 'Lim', english: 'Glue', context: 'Lim det sammen.' },
            { norwegian: 'Teip', english: 'Tape', context: 'Har du teip?' },
            { norwegian: 'Linjal', english: 'Ruler', context: 'Mål lengden med en linjal.' },
            { norwegian: 'Blyant', english: 'Pencil', context: 'Skriv med blyant.' },
            { norwegian: 'Viskelær', english: 'Eraser', context: 'Bruk viskelær hvis du gjør feil.' },
            { norwegian: 'Konvolutt', english: 'Envelope', context: 'Brevet ligger i konvolutten.' },
            { norwegian: 'Frimerke', english: 'Stamp', context: 'Sett frimerke på brevet.' },
            { norwegian: 'Batteri', english: 'Battery', context: 'Batteriet er tomt.' },
            { norwegian: 'Lader', english: 'Charger', context: 'Hvor er laderen min?' },
        ]
    },

    // Group: Level 2: Abstract & Descriptive Concepts
    adjectives_l2: {
        title: 'Adjectives (L2)',
        group: 'Level 2: Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'Kjedelig', english: 'Boring', context: 'Filmen var kjedelig.' },
            { norwegian: 'Spennende', english: 'Exciting', context: 'Boken er spennende.' },
            { norwegian: 'Farlig', english: 'Dangerous', context: 'Det er farlig å leke i veien.' },
            { norwegian: 'Trygg', english: 'Safe', context: 'Her er det trygt.' },
            { norwegian: 'Rask', english: 'Fast', context: 'Bilen er rask.' },
            { norwegian: 'Sakte', english: 'Slow', context: 'Skilpadden går sakte.' },
            { norwegian: 'Tung', english: 'Heavy', context: 'Steinen er tung.' },
            { norwegian: 'Lett', english: 'Light (weight)', context: 'Fjæren er lett.' },
            { norwegian: 'Mørk', english: 'Dark', context: 'Det er mørkt ute.' },
            { norwegian: 'Lys', english: 'Light/Bright', context: 'Rommet er lyst.' },
        ]
    },
    frequency_l2: {
        title: 'Frequency (L2)',
        group: 'Level 2: Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'Daglig', english: 'Daily', context: 'Jeg leser avisen daglig.' },
            { norwegian: 'Ukentlig', english: 'Weekly', context: 'Vi har møte ukentlig.' },
            { norwegian: 'Månedlig', english: 'Monthly', context: 'Lønnen kommer månedlig.' },
            { norwegian: 'Årlig', english: 'Yearly', context: 'Vi reiser årlig.' },
            { norwegian: 'Av og til', english: 'Occasionally', context: 'Jeg spiser godteri av og til.' },
            { norwegian: 'Hele tiden', english: 'All the time', context: 'Han snakker hele tiden.' },
            { norwegian: 'Straks', english: 'Immediately/Soon', context: 'Jeg kommer straks.' },
            { norwegian: 'Senere', english: 'Later', context: 'Vi sees senere.' },
            { norwegian: 'Tidligere', english: 'Earlier', context: 'Jeg kom tidligere i dag.' },
            { norwegian: 'Vanligvis', english: 'Usually', context: 'Jeg står vanligvis opp klokken syv.' },
        ]
    },
    questions_l2: {
        title: 'Questions (L2)',
        group: 'Level 2: Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'Hvor ofte', english: 'How often', context: 'Hvor ofte trener du?' },
            { norwegian: 'Hvor gammel', english: 'How old', context: 'Hvor gammel er du?' },
            { norwegian: 'Hvor stor', english: 'How big', context: 'Hvor stor er leiligheten?' },
            { norwegian: 'Hvorfor det', english: 'Why so/that', context: 'Hvorfor det?' },
            { norwegian: 'Hva skjedde', english: 'What happened', context: 'Hva skjedde her?' },
            { norwegian: 'Hvem der', english: 'Who is there', context: 'Hvem der?' },
            { norwegian: 'Hvilken vei', english: 'Which way', context: 'Hvilken vei skal vi gå?' },
            { norwegian: 'Når da', english: 'When then', context: 'Når da?' },
            { norwegian: 'Hva mer', english: 'What else', context: 'Hva mer trenger vi?' },
            { norwegian: 'Er det sant', english: 'Is it true', context: 'Er det sant at du skal flytte?' },
        ]
    },
    // Group: Essential Concrete Concepts
    animals: {
        title: 'Animals',
        group: 'Essential Concrete Concepts',
        words: [
            { norwegian: 'Hund', english: 'Dog', context: 'Hunden bjeffer høyt.' },
            { norwegian: 'Katt', english: 'Cat', context: 'Katten sover i sofaen.' },
            { norwegian: 'Fugl', english: 'Bird', context: 'Fuglen flyr i luften.' },
            { norwegian: 'Fisk', english: 'Fish', context: 'Fisken svømmer i vannet.' },
            { norwegian: 'Hest', english: 'Horse', context: 'Hesten løper fort.' },
            { norwegian: 'Ku', english: 'Cow', context: 'Kua spiser gress.' },
            { norwegian: 'Gris', english: 'Pig', context: 'Grisen liker å rulle i gjørme.' },
            { norwegian: 'Sau', english: 'Sheep', context: 'Sauen har myk ull.' },
            { norwegian: 'Ulv', english: 'Wolf', context: 'Ulven uler mot månen.' },
            { norwegian: 'Bjørn', english: 'Bear', context: 'Bjørnen sover om vinteren.' },
            { norwegian: 'Mus', english: 'Mouse', context: 'Musen spiser ost.' },
            { norwegian: 'Elefant', english: 'Elephant', context: 'Elefanten er veldig stor.' },
            { norwegian: 'Løve', english: 'Lion', context: 'Løven er dyrenes konge.' },
            { norwegian: 'Tiger', english: 'Tiger', context: 'Tigeren har striper.' },
            { norwegian: 'Ape', english: 'Monkey', context: 'Apen klatrer i trærne.' },
            { norwegian: 'Kanin', english: 'Rabbit', context: 'Kaninen hopper rundt.' },
            { norwegian: 'Kylling', english: 'Chicken', context: 'Kyllingen legger egg.' },
            { norwegian: 'And', english: 'Duck', context: 'Anden svømmer i dammen.' },
            { norwegian: 'Geit', english: 'Goat', context: 'Geita klatrer i fjellet.' },
            { norwegian: 'Rev', english: 'Fox', context: 'Reven er lur.' },
        ]
    },
    verbs_l2: {
        title: 'Verbs (L2)',
        group: 'Level 2: Abstract & Descriptive Concepts',
        words: [
            { norwegian: 'Å tenke', english: 'To think', context: 'Jeg liker å tenke.' },
            { norwegian: 'Å tro', english: 'To believe', context: 'Jeg tror på deg.' },
            { norwegian: 'Å vite', english: 'To know', context: 'Jeg vet svaret.' },
            { norwegian: 'Å huske', english: 'To remember', context: 'Jeg husker ikke navnet.' },
            { norwegian: 'Å glemme', english: 'To forget', context: 'Ikke glem nøklene.' },
            { norwegian: 'Å like', english: 'To like', context: 'Jeg liker is.' },
            { norwegian: 'Å elske', english: 'To love', context: 'Jeg elsker deg.' },
            { norwegian: 'Å hate', english: 'To hate', context: 'Jeg hater regn.' },
            { norwegian: 'Å ønske', english: 'To wish/want', context: 'Jeg ønsker meg en hund.' },
            { norwegian: 'Å håpe', english: 'To hope', context: 'Jeg håper det går bra.' },
        ]
    }
};

async function seedCategories() {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');

        // Clear existing categories
        await Category.deleteMany({});
        console.log('Cleared existing categories');

        // Insert categories
        const categoriesToInsert = Object.entries(CATEGORIES_DATA).map(([key, data]) => ({
            key,
            ...data
        }));

        await Category.insertMany(categoriesToInsert);
        console.log(`Seeded ${categoriesToInsert.length} categories`);

        mongoose.connection.close();
        console.log('Done!');
    } catch (error) {
        console.error('Error seeding categories:', error);
        process.exit(1);
    }
}

seedCategories();
